--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

-- Started on 2025-05-02 16:35:40

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16742)
-- Name: todolist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.todolist (
                                 id bigint NOT NULL,
                                 description character varying(255),
                                 status character varying(255),
                                 titre character varying(255),
                                 CONSTRAINT todolist_status_check CHECK (((status)::text = ANY ((ARRAY['A_FAIRE'::character varying, 'EN_COURS'::character varying, 'TERMINE'::character varying])::text[])))
);


ALTER TABLE public.todolist OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16741)
-- Name: todolist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.todolist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.todolist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4835 (class 0 OID 16742)
-- Dependencies: 216
-- Data for Name: todolist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.todolist (id, description, status, titre) FROM stdin;
1	Aller au supermarché pour acheter des fruits, du lait, du pain et du riz.	A_FAIRE	Acheter des courses
2	Compiler les statistiques de vente d’avril et envoyer le rapport à la direction.	EN_COURS	Finaliser le rapport mensuel
3	 Vider le lave-vaisselle, nettoyer les plans de travail et sortir les poubelles.	TERMINE	Nettoyer la cuisine
4	 Refaire les exercices sur les classes, les interfaces et les collections.	A_FAIRE	Réviser le cours de Java
5	 Prendre rendez-vous pour un bilan de santé annuel.	EN_COURS	Réviser le cours de Java
6	Vérifier les tests, mettre à jour les dépendances, puis faire le déploiement en production.	TERMINE	Déployer la version 1.2 de l’application
\.


--
-- TOC entry 4841 (class 0 OID 0)
-- Dependencies: 215
-- Name: todolist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.todolist_id_seq', 6, true);


--
-- TOC entry 4690 (class 2606 OID 16749)
-- Name: todolist todolist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.todolist
    ADD CONSTRAINT todolist_pkey PRIMARY KEY (id);


-- Completed on 2025-05-02 16:35:40

--
-- PostgreSQL database dump complete
--

